### PR TITLE
Fixed the compilation error on rustc-1.58.1

### PR DESCRIPTION
**Pull request by gaurishg**
image

Reordered generic parameters in impl in the order - lifetimes, types and then constants as required by Rust compiler.

### CODE REVIEW

**Comment by stephaneyfx** [comment]
What is the motivation for this change? Rust 1.58.1 cannot compile `enum-iterator` `1.2.0` for other reasons:
- `T: Sequence` in `const fn`.
- `core::array::from_fn` is unstable.

This crate tracks stable Rust and is not guaranteed to work with older versions.

**Comment by gaurishg** [comment]
This seemed to me a innocent change which will help in increasing compiler targets without any change in functionality. However if supporting older compilers is not the goal, it could be closed.

**Comment by stephaneyfx** [comment]
> [...] a innocent change which will help in increasing compiler targets [...]

This PR does not make the crate compile with Rust 1.58.1. It fixes one error, but there are other errors as mentioned in my previous message.

**Comment by stephaneyfx** [comment]
Thank you for your PR. Given that it does not make this crate compile with Rust 1.58.1 (there are other errors), I am closing this PR.
