### ISSUE TITLE
Unstable library

### ISSUE THREAD

**Issue by red-avtovo** [stephaneyfx/enum-iterator#20]
Hi! Thank you for making that great library!
I would like to know when you plan to switch to a stable track back?  I'm trying to build your lib on Rust stable and receive the following errors:
```
error[E0658]: use of unstable library feature 'array_from_fn'
   --> /Users/abochev/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.2.0/src/lib.rs:554:18
    |
554 |             Some(core::array::from_fn(|_| unreachable!()))
    |                  ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information

error[E0658]: use of unstable library feature 'array_from_fn'
   --> /Users/abochev/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.2.0/src/lib.rs:557:18
    |
557 |             Some(core::array::from_fn(|_| x.clone()))
    |                  ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information

error[E0658]: use of unstable library feature 'array_from_fn'
   --> /Users/abochev/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.2.0/src/lib.rs:563:18
    |
563 |             Some(core::array::from_fn(|_| unreachable!()))
    |                  ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information

error[E0658]: use of unstable library feature 'array_from_fn'
   --> /Users/abochev/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.2.0/src/lib.rs:566:18
    |
566 |             Some(core::array::from_fn(|_| x.clone()))
    |                  ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #89379 <https://github.com/rust-lang/rust/issues/89379> for more information
```

**Comment by stephaneyfx** [comment]
Hi! Thank you for your kind words. `enum-iterator` builds with the latest stable Rust 1.64.0. May you check the output of the following command?
```sh
rustc --version
```

**Comment by stephaneyfx** [comment]
`core::array::from_fn` [was stabilized in Rust 1.63.0](https://doc.rust-lang.org/src/core/array/mod.rs.html#38).

**Comment by red-avtovo** [comment]
You are so right!
I have an outdated Rust version
```
rustc 1.59.0 (9d1b2106e 2022-02-23)
```

Sorry for creating noise. Thank you for solving this mystery of mine

**Comment by stephaneyfx** [comment]
Don't be sorry; that's no problem. You're welcome and I am glad your issue is resolved.
