### ISSUE TITLE
New releases won't build on rust v1.60

### ISSUE THREAD

**Issue by CriesofCarrots** [stephaneyfx/enum-iterator#12]
Looks like v1+ requires rust v1.61.0 to build. Is that your intended MSV?

```
$ git checkout 1.0.0
$ cargo +1.60.0 build
   Compiling enum-iterator v1.0.0 (/enum-iterator/enum-iterator)
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
  --> enum-iterator/src/lib.rs:78:26
   |
78 | pub const fn cardinality<T: Sequence>() -> usize {
   |                          ^
   |
   = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information

For more information about this error, try `rustc --explain E0658`.
```

**Comment by stephaneyfx** [comment]
`enum-iterator` implicitly tracks stable Rust. Minor releases of this crate may require a newer Rust version. Patch releases must not require a newer Rust version.

**Comment by CriesofCarrots** [comment]
Got it. Might be nice to make that explicit?

**Comment by stephaneyfx** [comment]
A note about the Rust version was added in 4c92be12e67522df215fe344858362f3c021d1ef.
